import hagoromo1 from "./images/hagoromo1.jpeg";
import hagoromo2 from "./images/hagoromo2.jpg";
import hagoromo3 from "./images/hagoromo3.jpg";
export const STORES_INFO = [
    {
        id: 0,
        store: "Amazon",
        homePage: "https://www.amazon.com/",
        itemName: ["Hagoromo Chalk", "CPU", "Graphics Card"],
        allItems: [
            {
                id: 0,
                name: "Hagaromo Chalk 1",
                price: 5,
                image: hagoromo1,
                route: "amazon0",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 1,
                name: "Hagaromo Chalk 2",
                price: 10,
                image: hagoromo2,
                route: "amazon1",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 2,
                name: "Hagaromo Chalk 3",
                price: 15,
                image: hagoromo3,
                route: "amazon2",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 3,
                name: "Hagaromo Chalk 4",
                price: 20,
                image: hagoromo1,
                route: "amazon3",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 4,
                name: "Hagaromo Chalk 5",
                price: 25,
                image: hagoromo2,
                route: "amazon4",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 5,
                name: "Hagaromo Chalk 6",
                price: 30,
                image: hagoromo3,
                route: "amazon5",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 6,
                name: "Hagaromo Chalk 7",
                price: 35,
                image: hagoromo1,
                route: "amazon6",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
        ],
        itemRoute: ["hagoromo-chalk", "cpu", "graphicsCard"],
        price: [10, 20, 30],
        image: [
            [hagoromo1, hagoromo2, hagoromo3],
            [hagoromo2, hagoromo1],
            "Image 3",
        ],
        description:
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis quos cumque obcaecati aspernatur assumenda ipsam, voluptatibus aliquid nam omnis eveniet iure facilis esse eaque non quasi voluptatem quae repudiandae exercitationem.",
        link: [
            "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            "https://www.amazon.com/Amazon-Basics-Bater%C3%ADa-alcalina-23A/dp/B07GNMFLKH?ref_=ast_sto_dp&th=1&psc=1",
            "https://www.amazon.com/SBD85WD/dp/B06X6H2WF7?ref_=ast_sto_dp&th=1",
        ],
    },
    {
        id: 1,
        store: "Ebay",
        homePage: "https://www.ebay.com/",
        itemName: ["iPad", "iPhone", "MAC Book Pro"],
        allItems: [
            {
                id: 0,
                name: "Hagaromo Chalk",
                price: 40,
                image: hagoromo1,
                route: "ebay0",

                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 1,
                name: "Hagaromo Chalk",
                price: 45,
                image: hagoromo1,
                route: "ebay1",

                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 2,
                name: "Hagaromo Chalk",
                price: 50,
                image: hagoromo1,
                route: "ebay2",

                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 3,
                name: "Hagaromo Chalk",
                price: 55,
                image: hagoromo1,
                route: "ebay3",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 4,
                name: "Hagaromo Chalk",
                price: 60,
                image: hagoromo1,
                route: "ebay4",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            ,
            {
                id: 5,
                name: "Hagaromo Chalk",
                price: 60,
                image: hagoromo1,
                route: "ebay5",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            ,
            {
                id: 6,
                name: "HagoromoChalk",
                price: 60,
                image: hagoromo1,
                route: "ebay6",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
        ],
        itemRoute: ["iPad", "iPhone", "MACBookPro"],
        price: [40, 50, 60],
        image: [[hagoromo3, hagoromo2, hagoromo1], "Image 2", "Image 3"],
        description:
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis quos cumque obcaecati aspernatur assumenda ipsam, voluptatibus aliquid nam omnis eveniet iure facilis esse eaque non quasi voluptatem quae repudiandae exercitationem.",
        link: [
            "https://www.amazon.com/-/es/Edred%C3%B3n-relleno-hipoalerg%C3%A9nico-costuras-cuadros/dp/B07SFM6NXZ/ref=sr_1_1?qid=1656419943&sr=8-1",
            "https://www.amazon.com/Amazon-Basics-Bater%C3%ADa-alcalina-23A/dp/B07GNMFLKH?ref_=ast_sto_dp&th=1&psc=1",
            "https://www.amazon.com/SBD85WD/dp/B06X6H2WF7?ref_=ast_sto_dp&th=1",
        ],
    },
    {
        id: 2,
        store: "New-Egg",
        homePage: "https://www.newegg.com/",
        itemName: ["Gaming Chair", "Desktop", "Headphones"],
        allItems: [
            {
                id: 0,
                name: "Test 1",
                price: 65,
                image: hagoromo1,
                route: "newegg0",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 1,
                name: "Hagaromo Chalk 1",
                price: 70,
                image: hagoromo1,
                route: "newegg1",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 2,
                name: "Hagaromo Chalk 2",
                price: 75,
                image: hagoromo1,
                route: "newegg2",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            {
                id: 3,
                name: "Hagaromo Chalk 3",
                price: 80,
                image: hagoromo1,
                route: "newegg3",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            ,
            {
                id: 4,
                name: "Hagaromo Chalk 4",
                price: 80,
                image: hagoromo1,
                route: "newegg4",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            ,
            {
                id: 5,
                name: "Hagaromo Chalk 5",
                price: 80,
                image: hagoromo1,
                route: "newegg5",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
            ,
            {
                id: 6,
                name: "Hagaromo Chalk",
                price: 80,
                image: hagoromo1,
                route: "newegg6",
                link: "https://www.amazon.com/HAGOROMO-Fulltouch-Color-Chalk-White/dp/B01HDNUXBW?th=1",
            },
        ],
        itemRoute: ["gamingChair", "Desktop", "Headphones"],
        price: [70, 80, 90],
        image: [[hagoromo2, hagoromo3, hagoromo1], "Image 2", "Image 3"],
        description:
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis quos cumque obcaecati aspernatur assumenda ipsam, voluptatibus aliquid nam omnis eveniet iure facilis esse eaque non quasi voluptatem quae repudiandae exercitationem.",
        link: [
            "https://www.amazon.com/-/es/Edred%C3%B3n-relleno-hipoalerg%C3%A9nico-costuras-cuadros/dp/B07SFM6NXZ/ref=sr_1_1?qid=1656419943&sr=8-1",
            "https://www.amazon.com/Amazon-Basics-Bater%C3%ADa-alcalina-23A/dp/B07GNMFLKH?ref_=ast_sto_dp&th=1&psc=1",
            "https://www.amazon.com/SBD85WD/dp/B06X6H2WF7?ref_=ast_sto_dp&th=1",
        ],
    },
];

export const AMAZON_ITEMS = [
    {
        id: 0,
        image: "image1",
        name: "Shirt",
        route: "shirt/route",
        price: 15,
    },
    {
        id: 0,
        image: "image2",
        name: "Shirt",
        route: "shirt/route",
        price: 5,
    },
    {
        id: 0,
        image: "image3",
        name: "Shirt",
        route: "shirt/route",
        price: 20,
    },
    {
        id: 0,
        image: "image4",
        name: "Shirt",
        route: "shirt/route",
        price: 30,
    },
];
